name: CI/CD pipeline lab 9 

on:
  push:
    branches:
      - main
      - lab9
    paths:
      - '!docs/**'
      - '**'
  pull_request:
    paths:
      - '!docs/**'
      - '**'
  workflow_dispatch:
    inputs:
      run_static_analysis:
        description: 'Run static analysis (linter and type checking) ?'
        default: 'true'
        required: true
      run_tests:
        description: 'Run tests ?'
        default: 'true'
        required: true
  schedule:
    - cron: "0 8 * * 1" 
    
    
env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare pnpm@latest-8 --activate
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Build
        run: pnpm build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: dist/

  test-and-analyze:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        
      - name: Install dependencies
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare pnpm@latest-8 --activate
          pnpm config set store-dir .pnpm-store
          pnpm install
        
      - name: Run linter
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_static_analysis == 'true'
        run: pnpm lint
        
      - name: Run static type checking
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_static_analysis == 'true'
        run: pnpm type-check
        
      - name: Run unit tests
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_tests == 'true'
        run: pnpm test

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare pnpm@latest-8 --activate
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}  
          path: dist/

      - name: Deploy to QA
        env:
          AZURE_TOKEN_QA: ${{ secrets.AZURE_TOKEN_QA }}
        run: pnpm dlx @azure/static-web-apps-cli deploy ./dist --token $AZURE_TOKEN_QA --app-name stapp-vue2048-QA --environment production
          #pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-QA --env=production 
  

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare pnpm@latest-8 --activate
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}  
          path: dist/

      - name: Deploy to Production
        run: pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-prod --env=production 
  

      
