name: CI/CD pipeline lab 9

on:
  push:
    branches:
      - main
    paths:
      - '!docs/**'
      - '**'
  pull_request:
    paths:
      - '!docs/**'
      - '**'
  workflow_dispatch:
    inputs:
      run_static_analysis:
        description: 'Run static analysis?'
        default: 'true'
        required: true
      run_tests:
        description: 'Run tests?'
        default: 'true'
        required: true
  schedule:
    - cron: "0 8 * * 1" 
    
    
env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
