name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build application
        run: |
          # Commande pour construire l'application
          # Assurez-vous de générer un package et de le stocker comme un artifact

      - name: Run static analysis and unit tests
        run: |
          # Commandes pour exécuter les analyses statiques (linter, typage statique) et les tests unitaires

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy to QA
        run: |
          # Commande pour déployer l'application sur l'environnement QA

      - name: Deploy to PROD
        run: |
          # Commande pour déployer l'application sur l'environnement de production
